config/routes.rb
Clantwgb::Application.routes.draw do

  match '/rules', to: 'pages#rules'
  match '/report_abuse', to: 'pages#report_abuse'
  match '/stats', to: 'users#index'
  match '/admin_application', to: 'pages#admin_application'
  match '/abuse', to: 'pages#abuse'
  match '/contact', to: 'pages#contact'

  resources :games, only: [:index, :show] do
    member do
      get 'download_replay'
    end
  end

  resources :users

  resources :ghost_mmd_users, only: [:index, :show] do
  end

  root to: 'pages#home'

  match '/botstatus.html' => "bot_status#get_game_info"
  match '/bot-getgames.php' => "bot_status#update_game_info"

end

app/views/pages/home.html.haml
.container-fluid
	.row-fluid
		.span12
			%h1 Clan TwGB
			We are an Island Troll Tribes clan on Warcraft III. Our home channel is Clan TwGB @ Azeroth (US East). We host the most current version of Island Troll Tribes on a 24/7 hostbot. It is also connected to US West and Europes battle.net servers.

app/views/pages/rules.html.haml
.container-fluid
  .row-fluid
    .span12
      :markdown
        ## General Rules
        1. Do NOT spam commands to any of the bots, this includes
           the stealthbot and the host bot. If any bots become
           banned on battle.net due to you spamming it, you will
           be perma banned.
        2. Please respect TwGB Shamans, they are here to help you.
        3. If you want admin you have apply via the site (click on
           admin applications). Grunts mean you are hostbot admin,
           peons are non-admin.
        4. Team killing IS NOT A PART OF THE GAME! Admins will kick
           on site and Shamans may ban you for it. 
        5. If a "trick" is found to be a glitch by the ITT community,
           then don't do it.
        6. If you leave multiple games for unjustified reasons you
           can be banned temporarily
        7. Rushing, the act of going onto another players island and
           killing them, is permitted in all TwGB games. However,
           spawn camping, the act of killing a player after they spawn
           and have attempted to run away, is not permitted. It is
           dealt with by either a kick or in severe cases a ban. Since
           all spawn camps are different, here are some guide lines to
           follow:
           - If you feel like you are being camped at your spawn, the
             first thing you must try is running away in a direction
             which is not controlled by your enemy
           - If you are incapable of running away because there are no
             paths of escape **and** you are being killed before you can
             get away you are trully being spawn camped. The best thing
             to do in this situation is notify TwGB Staff and submit an
             [abuse report](#{report_abuse_path})
        8. If someone on a team is found to be purposefully feeding
           another team, (feeding is when they go to other teams spawns
           with the intent of to be killed by other team, twice) that
           person is to be banned.  A replay is needed in order to prove
           that this is happening.
        9. No smurfing! (Creating secondary accounts) just to get a better
           score.  Your newer account WILL be erased from stats, and banned
           on the bot on FIRST offense!  Play fair, or don't play at all.

        ## Rules for Administrators and Shamans

        1. Do not close slots below what would be a 4 player game when you
           will start the game your self.
        2. Do not close slots below the autostart value if you don't plan on
           staying in game.  If you plan on leaving a game you have altered,
           either start the game for the other players, or open slots again
           to create a 3v3 game and set the autostart value to 6.
        3. Do not unban players that are banned, removing a ban will result
           in your loosing admin and being banned for 14 days.
        4. **Only shamans** will invoke bans upon players that violate rules
           by issuing the ban in channel by typing .gban username days rule
           violation/reason      
           Example: .gban c0rr0sive 3 Broke rule 14. This results in a 3 day
           ban, for that user, with that reason.  The ban will be auto-lifted.
        5. If you participate in PRIVATE betas, do not leak information to
           players not in the beta, we don't need to get their hopes up if
           something doesn't make it into a final version.
        6. If you are accused of cheating, save your replay, and do an Admin
           report, if abuse is submitted against you, we will look at your
           reports and request the replay from you.
        7. Do NOT EVER kick players that are not in violation of rules, you may
           however start a vote kick.
        8. Admins if you would like to see a player banned, please fillout the
           small form at the abuse report section.