config/routes.rb
Clantwgb::Application.routes.draw do

  match '/rules', to: 'pages#rules'
  match '/report_abuse', to: 'pages#report_abuse'
  match '/stats', to: 'users#index'
  match '/admin_application', to: 'pages#admin_application'
  match '/abuse', to: 'pages#abuse'
  match '/contact', to: 'pages#contact'

  resources :games, only: [:index, :show] do
    member do
      get 'download_replay'
    end
  end

  resources :users

  resources :ghost_mmd_users, only: [:index, :show] do
  end

  root to: 'pages#home'

  match '/botstatus.html' => "bot_status#get_game_info"
  match '/bot-getgames.php' => "bot_status#update_game_info"

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = GhostGame.where("gamename LIKE ?", "%TwGB%").order("datetime desc").limit(25)
    @no_side_bar = true
  end
  def show
    @game  = GhostGame.find(params[:id], include: [:users])
  end
  def download_replay
    @game = GhostGame.find(params[:id])
    send_file @game.replay_path
  end
end

app/views/games/_show.html.haml
%section
  %h1= game.gamename

  %label Map
  .value= game.map

  %label Date
  .value= game.datetime

  %label Length
  .value= "#{game.duration}m"

  - if game.replay_path
    %label Download Replay
    .value= link_to File.basename(game.replay_path), download_replay_game_path(game)

app/views/games/_table.html.haml
%table
  %thead
    %tr
      %th Name
      %th Map
      %th Date/Time
      %th Duration

  %tbody
    - games.each do |game|
      %tr
        %td
          = link_to game.gamename, game_path(game)
        %td= game.map
        %td= game.datetime
        %td= "#{game.duration}m"

app/views/games/index.html.haml
= render partial: 'table', locals: { games: @games }

app/views/games/show.html.haml
= render partial: 'games/show', locals: { game: @game }

= render partial: 'ghost_mmd_users/table', locals: { users: @game.users }

- if Rails.env.development?
  %section.debug
    %pre{style:"width:100%;white-space: pre-wrap;"}
      = @game.inspect
      = @game.users.inspect
      = @game.users_info.inspect