config/routes.rb
Clantwgb::Application.routes.draw do

  match '/rules', to: 'pages#rules'
  match '/report_abuse', to: 'pages#report_abuse'
  match '/stats', to: 'users#index'
  match '/admin_application', to: 'pages#admin_application'
  match '/abuse', to: 'pages#abuse'
  match '/contact', to: 'pages#contact'

  resources :games, only: [:index, :show] do
    member do
      get 'download_replay'
    end
  end

  resources :users

  resources :ghost_mmd_users, only: [:index, :show] do
  end

  root to: 'pages#home'

  match '/botstatus.html' => "bot_status#get_game_info"
  match '/bot-getgames.php' => "bot_status#update_game_info"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    /
      Created by Quazz
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title Clan TwGB
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:content => "Website for Clan TwGB Warcraft III Island Troll Tribes custom games. Has stats, info, forums, and more.", :name => "description"}/
    %meta{:content => "island troll tribes clan twgb", :name => "keywords"}
    %link{:href => "/favicon.ico", :rel => "shortcut icon"}
    %link{href:'//fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic', rel:'stylesheet', type:'text/css'}
  %body
    %section#servers.hidden{style:"display:none;"}
      Server:
      %a{href: "http://classic.battle.net/war3/ladder/w3xp-clan-profile.aspx?Gateway=Azeroth&ClanTag=TwGB", target: "_blank"} useast.battle.net
      %br/
      Server:
      %a{href: "http://classic.battle.net/war3/ladder/w3xp-clan-profile.aspx?Gateway=Lordaeron", target: "_blank"} uswest.battle.net
      %br/
      Server:
      %a{href: "http://classic.battle.net/war3/ladder/w3xp-clan-profile.aspx?Gateway=Northrend&ClanTag=ITTP", target: "_blank"} europe.battle.net
      %br/
    #art-main
      .art-sheet
        .art-sheet-tl
        .art-sheet-tr
        .art-sheet-bl
        .art-sheet-br
        .art-sheet-tc
        .art-sheet-bc
        .art-sheet-cl
        .art-sheet-cr
        .art-sheet-cc
        .art-sheet-body
          .art-header
            .art-header-clip
              .art-header-center
                .art-header-png
                .art-header-jpeg
            .art-logo
              %h1.art-logo-name
                %a{:href => "/"} Island Troll Tribes
              %h2.art-logo-text TwGB
          .cleared.reset-box
          .art-nav
            .art-nav-l
            .art-nav-r
            .art-nav-outer
              %ul.art-hmenu
                %li
                  = link_to root_path, class: 'l' do
                    %span.l
                    %span.r
                    %span.t TwGB Home
                %li
                  = link_to stats_path, class: 'l' do
                    %span.l
                    %span.r
                    %span.t Stats
                %li
                  = link_to games_path, class: 'l' do
                    %span.l
                    %span.r
                    %span.t Games
                %li
                  = link_to admin_application_path, class: 'l' do
                    %span.l
                    %span.r
                    %span.t Admin Application
                %li
                  = link_to rules_path, class: 'l' do
                    %span.l
                    %span.r
                    %span.t TwGB Rules
                %li
                  = link_to abuse_path, class: 'l' do
                    %span.l
                    %span.r
                    %span.t Report Player Abuse
                %li
                  = link_to contact_path, class: 'l' do
                    %span.l
                    %span.r
                    %span.t Contact TwGB
                %li
                  = link_to "http://www.clantwgb.com/forums", class: 'l' do
                    %span.l
                    %span.r
                    %span.t TwGB Forums
          .cleared.reset-box
          .art-content-layout
            .art-content-layout-row
              .art-layout-cell.art-content
                .art-post
                  .art-post-body
                    .art-post-inner.art-article
                      .cleared
                      .art-postcontent
                        = yield
                      .cleared
                    .cleared
                .cleared
              = render partial: 'layouts/left_sidebar' unless defined? @no_side_bar
          .cleared
          .art-footer
            .art-footer-t
            .art-footer-l
            .art-footer-b
            .art-footer-r
            .art-footer-body
              .art-footer-text{style:"text-align:center;"}
                = link_to "Shaman Console", "http://shaman.clantwgb.com"
              .cleared
          .cleared
      .cleared